/** State verbs */
export const DEFAULT_VERB = 'Existing'
export const IDLE_VERB = 'Just chillin\''
export const EAT_VERB = 'Eating'
export const SLEEP_VERB = 'Asleep'
export const EGG_VERB = 'Egg'
export const HATCH_VERB = 'It\'s about to hatch!'
export const ARM_VERB = 'Doing curls'
export const DOG_VERB = 'Playing with dogs'
export const HAIR_VERB = 'Getting hair brushed'
export const INCUBATE_VERB = 'Incubating'
export const TASTE_VERB = 'Scarfing down hot dogs'
export const SIGHT_VERB = 'Reading a book'
export const CORE_VERB = 'Doing situps'
export const LEG_VERB = 'Doing squats'
export const MEME_VERB = 'Surfing the web'
export const EXERT_VERB = 'Getting swole'

/** Text Emojis */
export const BABY_EMOJI = '\u{1F476}'
export const IDLE_EMOJI = '\u{1F642}'
export const EXERT_EMOJI = '\u{1F605}'
export const ASLEEP_EMOJI = '\u{1F634}'
